/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clac;

/**
 *
 * @author User
 */
public class clacInterface extends javax.swing.JFrame {

    /**
     * Creates new form clacInterface
     */
    public clacInterface() {
        initComponents();
    }
    
    Stack numberStack = new Stack(5);
    boolean flag = false;
    double sum=0.0;
    String operation = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtdisplay = new javax.swing.JTextField();
        btnequal = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnsub = new javax.swing.JButton();
        btnmultiply = new javax.swing.JButton();
        btndivide = new javax.swing.JButton();
        btnsqrt = new javax.swing.JButton();
        btnpower1 = new javax.swing.JButton();
        txtoperation = new javax.swing.JTextField();
        btndecimal1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdisplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtdisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtdisplay.setEnabled(false);
        getContentPane().add(txtdisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 360, 60));

        btnequal.setText("=");
        btnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalActionPerformed(evt);
            }
        });
        getContentPane().add(btnequal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 83, 62));

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 83, 62));

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 83, 62));

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 83, 62));

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 83, 62));

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 83, 62));

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 83, 62));

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 83, 62));

        btndel.setText("CLR");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        getContentPane().add(btndel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 83, 62));

        btn10.setText("9");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 83, 62));

        btnclear.setText("CE");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 80, 62));

        btn11.setText("0");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        getContentPane().add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 83, 62));

        btn9.setText("1");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 83, 62));

        btnadd.setText("+");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 83, 62));

        btnsub.setText("-");
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubActionPerformed(evt);
            }
        });
        getContentPane().add(btnsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 83, 62));

        btnmultiply.setText("*");
        btnmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(btnmultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 83, 62));

        btndivide.setText("/");
        btndivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivideActionPerformed(evt);
            }
        });
        getContentPane().add(btndivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 83, 62));

        btnsqrt.setText("Sqrt");
        btnsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsqrtActionPerformed(evt);
            }
        });
        getContentPane().add(btnsqrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 80, 62));

        btnpower1.setText("POW");
        btnpower1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpower1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnpower1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 80, 62));

        txtoperation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtoperation.setEnabled(false);
        getContentPane().add(txtoperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 90, -1));

        btndecimal1.setText(".");
        getContentPane().add(btndecimal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 83, 62));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplyActionPerformed
        operation = "*";
        multiply();
    }//GEN-LAST:event_btnmultiplyActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        txtdisplay.setText(txtdisplay.getText() + "1");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        txtdisplay.setText(txtdisplay.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txtdisplay.setText(txtdisplay.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        txtdisplay.setText(txtdisplay.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        txtdisplay.setText(txtdisplay.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        txtdisplay.setText(txtdisplay.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        txtdisplay.setText(txtdisplay.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
       txtdisplay.setText(txtdisplay.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        txtdisplay.setText(txtdisplay.getText() + "9");
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        txtdisplay.setText(txtdisplay.getText() + "0");
    }//GEN-LAST:event_btn11ActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        txtdisplay.setText(null);
    }//GEN-LAST:event_btndelActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
            operation = "+";
            add();
      
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubActionPerformed
        operation = "-";
        subs();
    }//GEN-LAST:event_btnsubActionPerformed

    private void btndivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivideActionPerformed
        operation = "/";
        div();
    }//GEN-LAST:event_btndivideActionPerformed

    private void btnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalActionPerformed
        switch (operation) {
            case "+":
                add();
                break;
            case "-":
                subs();
                break;
            case "*":
                multiply();
                break;
            case "/":
                div();
                break;
            case "pow":
                power();
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btnequalActionPerformed

    private void btnpower1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpower1ActionPerformed
        operation = "pow";
        power();
    }//GEN-LAST:event_btnpower1ActionPerformed

    private void btnsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsqrtActionPerformed

        numberStack.push(Double.parseDouble(txtdisplay.getText()));
            clear();
            //txtoperation.setText(numberStack.peek()+""); 
                if(numberStack.top>=1){
                double n2 = numberStack.peek();
                sum = Math.sqrt(n2);
                txtdisplay.setText(String.valueOf(sum));
                numberStack.pop();
                numberStack.pop(); 
                }
    }//GEN-LAST:event_btnsqrtActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        for (int i = 0; i <= numberStack.top; i++) {
            numberStack.pop();
        }
        txtdisplay.setText(null);
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clacInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clacInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clacInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clacInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new clacInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndecimal1;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btndivide;
    private javax.swing.JButton btnequal;
    private javax.swing.JButton btnmultiply;
    private javax.swing.JButton btnpower1;
    private javax.swing.JButton btnsqrt;
    private javax.swing.JButton btnsub;
    private javax.swing.JTextField txtdisplay;
    private javax.swing.JTextField txtoperation;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        txtdisplay.setText(null);
    }

    private void add() {
        numberStack.push(Double.parseDouble(txtdisplay.getText()));
            clear();
            //txtoperation.setText(numberStack.peek()+""); 
                if(numberStack.top>=1){
                double n1 = numberStack.peek();
                double n2 = numberStack.peek();
                sum = n1 + n2; 
                txtdisplay.setText(String.valueOf(sum));
                numberStack.pop();
                numberStack.pop(); 
                }
    }

    private void subs() {
        numberStack.push(Double.parseDouble(txtdisplay.getText()));
            clear();
            //txtoperation.setText(numberStack.peek()+""); 
                if(numberStack.top>=1){
                double n1 = numberStack.peek();
                double n2 = numberStack.peek();
                sum = n2 - n1; 
                txtdisplay.setText(String.valueOf(sum));
                numberStack.pop();
                numberStack.pop(); 
                }
    }

    private void div() {
    numberStack.push(Double.parseDouble(txtdisplay.getText()));
            clear();
            //txtoperation.setText(numberStack.peek()+""); 
                if(numberStack.top>=1){
                        double n1 = numberStack.peek();
                        double n2 = numberStack.peek();
                    if(n1!=0){
                        sum = n2 / n1; 
                        txtdisplay.setText(String.valueOf(sum));
                        numberStack.pop();
                        numberStack.pop();
                    }else{
                        txtdisplay.setText("Error");
                    }
 
                }    
    }

    private void multiply() {
    numberStack.push(Double.parseDouble(txtdisplay.getText()));
            clear();
            //txtoperation.setText(numberStack.peek()+""); 
                if(numberStack.top>=1){
                double n1 = numberStack.peek();
                double n2 = numberStack.peek();
                sum = n2 * n1; 
                txtdisplay.setText(String.valueOf(sum));
                numberStack.pop();
                numberStack.pop(); 
                }    
    }

    private void power() {
    numberStack.push(Double.parseDouble(txtdisplay.getText()));
            clear();
            //txtoperation.setText(numberStack.peek()+""); 
                if(numberStack.top>=1){
                double n1 = numberStack.peek();
                double n2 = numberStack.peek();
                sum = Math.pow(n2, n1);
                txtdisplay.setText(String.valueOf(sum));
                numberStack.pop();
                numberStack.pop(); 
                }    
    }
}

class Stack{
    double arr[];
    int top;
    int counter;
    int capacity;
    
    Stack(int size){
        arr =new double[size];
        top = -1;
        counter =0;
        capacity = size;
    }
    
    boolean isFull(){
        return top+1 == capacity;
    }
    int push(double x){
        if(isFull()){
            return -1;
        }
        else{
            top++;
            counter =top+1;
            arr[top]=x;
            return 0;
        }
    }
    boolean isEmpty(){
        return top == -1;
    }
    
    public double peek() {
        if (top == -1) {
            System.out.println("Stack is empty!");
            return -1;
        }
        counter = counter -1;
        return arr[counter];
    }
    int pop(){
        if(isEmpty()){
            return -1;
        }
        else{
            top--;
            return 0;
        }
    }
    void printStack(){
        for (int i = 0; i <=top; i++) {
            System.out.println(arr[i]);
        }
    }
}
